# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8084

spring:
  application:
    name: product
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://localhost:1433;databaseName=csjxc_net_chen
      #            ?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: user
      password: 123456
#      url: jdbc:sqlserver://www.chiuwah.co.uk:1433;databaseName=csjxc_net_chen
#      #            ?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: root
#      password: Chiuwah2021
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848


#spring:
#  datasource:
#    username: user
#    password: 123456
#    url: jdbc:sqlserver://localhost:1433;databaseName=csjxc_net_chen
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml



