spring:
  cloud:
    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:8001"
#            allowedMethods:
#              - GET POST
      routes:
        - id: item_category
          uri: https://www.baidu.com
          predicates:
            - Query=green

        - id: category_route
          uri: lb://product
          order: 0
          predicates:
            - Path=/api/category/**
          filters:
            - RewritePath=/api/category/?(?<segment>.*),/category/$\{segment}

        - id: product_route
          uri: lb://product
          order: 1
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product/?(?<segment>.*),/product/$\{segment}


        - id: admin_home
          uri: lb://renren-fast
          order: 2
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*),/renren-fast/$\{segment}

